Repository go-sprout/sprout, pull requests merged in 2024-08, with the labels that each got.

#48 fix: default logger have a bad init
  sprout.go
Labels: type/bug 🔥, priority/critical 🟥, domain/obvious 🟩, aspect/dex 🤖, state/done ✔

#50 fix: logger aren't accessible due to duplicated pointer
  docs/advanced/how-to-create-a-registry.md
  registry/_example/_example.go
  registry/backward/backward.go
  registry/checksum/checksum.go
  registry/conversion/conversion.go
  registry/crypto/crypto.go
  registry/encoding/encoding.go
  registry/env/env.go
  registry/filesystem/filesystem.go
  registry/maps/maps.go
  registry/numeric/numeric.go
  registry/random/random.go
  registry/reflect/reflect.go
  registry/regexp/regexp.go
  registry/semver/semver.go
  registry/slices/slices.go
  registry/std/std.go
  registry/strings/strings.go
  registry/time/time.go
  registry/uniqueid/uniqueid.go
Labels: priority/high 🟧, type/bug 🔥, aspect/dex 🤖, state/done ✔

#55 fix: sprigin camelcase needs to be the same (bugged) return
  sprigin/sprig_backward_compatibility.go
Labels: (╯°□°)╯︵ ┻━┻ 🤯, type/bug 🔥, domain/obvious 🟩, aspect/dex 🤖, priority/medium 🟨, state/done ✔

#54 chore: use go task instead of makefile
  .devcontainer/devcontainer.json
  .github/workflows/test.yaml
  Makefile
  benchmarks/Makefile
  benchmarks/comparaison_test.go
  taskfile.yml
Labels: type/chore 🛠, priority/low 🟩, domain/obvious 🟩, aspect/dex 🤖, state/done ✔

#52 chore: drop-off v0.1 error handling until rfc safe/must decision
  README.md
  docs/introduction/getting-started.md
  docs/migration-from-sprig.md
  error.go
  handler.go
  sprout.go
  sprout_test.go
Labels: type/chore 🛠, domain/obvious 🟩, aspect/dex 🤖, priority/medium 🟨, state/done ✔

#58 feat: add notice on function call to inform or warn the end-users
  benchmarks/comparaison_test.go
  handler.go
  handler_test.go
  notice.go
  notice_test.go
  registry.go
  registry/numeric/numeric.go
  sprigin/sprig_backward_compatibility.go
  sprout.go
Labels: priority/high 🟧, state/todo 🚀, domain/obvious 🟩, type/feature ⭐, aspect/dex 🤖

#59 feat: add sha512sum to checksum registry and add notices
  docs/registries/checksum.md
  registry/checksum/checksum.go
  registry/checksum/functions.go
  registry/checksum/functions_test.go
  sprigin/sprig_backward_compatibility_test.go
Labels: good first issue, priority/low 🟩, domain/obvious 🟩, type/feature ⭐, aspect/dex 🤖, state/done ✔

#61 feat: add `hasField` method for use with structs
  docs/registries/reflect.md
  registry/reflect/functions.go
  registry/reflect/functions_test.go
  registry/reflect/reflect.go
Labels: good first issue, priority/low 🟩, state/todo 🚀, domain/obvious 🟩, type/feature ⭐, aspect/dex 🤖

#62 feat: add strings capitalization functions
  docs/registries/strings.md
  registry/strings/functions.go
  registry/strings/functions_test.go
  registry/strings/strings.go
Labels: good first issue, priority/low 🟩, domain/obvious 🟩, type/feature ⭐, aspect/dex 🤖, state/done ✔

#63 fix: capitalize with unicode and latin runes
  registry/strings/functions.go
  registry/strings/functions_test.go
  registry/strings/helpers.go
Labels: priority/high 🟧, type/bug 🔥, aspect/dex 🤖, state/done ✔

#64 docs: add functions signature in conventions
  docs/introduction/templating-conventions.md
Labels: priority/high 🟧, type/chore 🛠, domain/obvious 🟩, aspect/documentation 📚, state/done ✔
