Repository go-sprout/sprout, pull requests merged in 2024-12, with the labels that each got.

#86 chore: update template examples for clarity and accuracy
  .github/workflows/test.yaml
  benchmarks/go.mod
  docs/registries/backward.md
  docs/registries/checksum.md
  docs/registries/conversion.md
  docs/registries/encoding.md
  docs/registries/env.md
  docs/registries/filesystem.md
  docs/registries/maps.md
  docs/registries/network.md
  docs/registries/numeric.md
  docs/registries/random.md
  docs/registries/reflect.md
  docs/registries/regexp.md
  docs/registries/slices.md
  docs/registries/std.md
  docs/registries/strings.md
  docs/registries/time.md
  docs/registries/uniqueid.md
  go.mod
  taskfile.yml
  tools/docvalidator/filesystem.go
  tools/docvalidator/main.go
  tools/docvalidator/main_test.go
  tools/docvalidator/parsing.go
  tools/docvalidator/parsing_test.go
  tools/docvalidator/processing.go
  tools/docvalidator/processing_test.go
Labels: priority/high 🟧

#97 doc: replace all go template example by doc link
  docs/roadmap-to-sprout-v1.0.md
  registry/_example/_example.go
  registry/_example/functions.go
  registry/backward/functions.go
  registry/backward/helpers.go
  registry/checksum/functions.go
  registry/checksum/helpers.go
  registry/conversion/functions.go
  registry/conversion/helpers.go
  registry/crypto/functions.go
  registry/crypto/helpers.go
  registry/encoding/functions.go
  registry/env/functions.go
  registry/filesystem/functions.go
  registry/maps/functions.go
  registry/network/functions.go
  registry/numeric/functions.go
  registry/numeric/helpers.go
  registry/random/functions.go
  registry/random/helpers.go
  registry/reflect/functions.go
  registry/reflect/functions_test.go
  registry/regexp/functions.go
  registry/semver/functions.go
  registry/slices/functions.go
  registry/slices/helpers.go
  registry/std/functions.go
  registry/strings/functions.go
  registry/strings/helpers.go
  registry/time/functions.go
  registry/uniqueid/functions.go
Labels: type/chore 🛠, priority/low 🟩, aspect/documentation 📚

#94 fix(date): use available timezone if any
  .golangci.yaml
  benchmarks/comparison_test.go
  docs/registries/conversion.md
  docs/registries/time.md
  handler.go
  pesticide/time_test_helpers.go
  registry/conversion/functions.go
  registry/conversion/functions_test.go
  registry/time/functions.go
  registry/time/functions_test.go
  registry/time/helpers.go
  registry/time/helpers_test.go
  sprigin/sprig_backward_compatibility.go
Labels: priority/medium 🟨
