Repository go-sprout/sprout, pull requests merged in 2024-06, with the labels that each got.

#38 chore: reduce yaml dependencies footprint
  encoding_functions.go
  encoding_functions_test.go
  go.mod
  go.sum
Labels: type/chore 🛠, priority/low 🟩, aspect/depencencies 📦️, domain/obvious 🟩

#42 fix: timezone leak in to date method
  conversion_functions_test.go
Labels: (╯°□°)╯︵ ┻━┻ 🤯, type/bug 🔥, domain/obvious 🟩, aspect/dex 🤖, priority/medium 🟨, state/done ✔

#43 docs: add documentation for backward compatibilities
  SPRIG_TO_SPROUT_CHANGES_NOTES.md
  numeric_functions.go
  sprig_backward_compatibility.go
Labels: type/chore 🛠, priority/low 🟩, domain/obvious 🟩, aspect/documentation 📚, state/done ✔
